export default {
  cms_manual_init: true,
  backend: {
    name: 'test-repo',
    repo: 'neontribe/my-best-life',
    branch: 'main',
  },
  publish_mode: 'editorial_workflow',
  media_folder: 'public/img',
  public_folder: 'img',
  editor: {
    preview: false,
  },
  collections: [
    {
      label: 'Service',
      label_singular: 'Services',
      name: 'service',
      folder: 'content/services',
      create: true,
      summary: '{{organisation}}: {{short-description}}',
      fields: [
        {
          label: 'Organisation',
          name: 'organisation',
          hint: 'The name of the organisation or charity that runs the service',
          widget: 'string',
        },
        {
          label: 'Short description',
          name: 'short-description',
          widget: 'string',
        },
        { label: 'Image', name: 'image', widget: 'image', required: false },
        {
          label: 'Description',
          name: 'description',
          widget: 'markdown',
          buttons: ['bold', 'italic', 'link'],
          editor_components: [],
          modes: ['raw', 'rich_text'],
        },
        {
          label: 'Category 1',
          name: 'category-1',
          widget: 'select',
          options: [
            { label: '-', value: '' },
            { label: 'Money', value: 'money' },
            { label: 'School and college', value: 'school-and-college' },
            { label: 'Sex and relationships', value: 'sex-and-relationships' },
            { label: 'Mental health', value: 'mental-health' },
            { label: 'Keeping safe', value: 'keeping-safe' },
            { label: 'Job stuff', value: 'job-stuff' },
            { label: "Where I'm living", value: 'where-im-living' },
            { label: 'Friends', value: 'friends' },
            { label: 'Family', value: 'family' },
            { label: 'Drink and drugs', value: 'drink-and-drugs' },
            { label: 'My body', value: 'my-body' },
            { label: 'My rights and the law', value: 'my-rights-and-the-law' },
          ],
        },
        {
          label: 'Category 2',
          name: 'category-2',
          widget: 'select',
          options: [
            { label: 'Money', value: 'money' },
            { label: 'School and college', value: 'school-and-college' },
            { label: 'Sex and relationships', value: 'sex-and-relationships' },
            { label: 'Mental health', value: 'mental-health' },
            { label: 'Keeping safe', value: 'keeping-safe' },
            { label: 'Job stuff', value: 'job-stuff' },
            { label: "Where I'm living", value: 'where-im-living' },
            { label: 'Friends', value: 'friends' },
            { label: 'Family', value: 'family' },
            { label: 'Drink and drugs', value: 'drink-and-drugs' },
            { label: 'My body', value: 'my-body' },
            { label: 'My rights and the law', value: 'my-rights-and-the-law' },
          ],
        },
      ],
    },
  ],
}
